export const SET_GALLERIES = 'SET_GALLERIES';
export const SET_SINGLE_GALLERY = 'SET_SINGLE_GALLERY';
export const ADD_NEW_GALLERY = 'ADD_NEW_GALLERY';
export const SEARCH_GALLERY = 'SEARCH_GALLERY';
export const INIT_GALLERIES = 'INIT_GALLERIES';

